package com.mealtalk.api.domain;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.MigrationVersion;
import org.flywaydb.core.api.output.MigrateResult;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class FoodOwnershipMigrationTests {
    @Test
    void freshDatabaseMigratesThroughV3ThenRequiresFoodOwnerAndPersistsArchiveState() throws Exception {
        String url = databaseUrl();

        assertEquals(migrationResource("/db/migration/V2__add_private_food_ownership.sql"),
            migrationResource("/db/migration-h2/V2__add_private_food_ownership.sql"));

        MigrateResult result = freshFlyway(url).migrate();

        assertEquals(3, result.migrationsExecuted);
        try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
            long ownerId = insertUser(connection, "fresh-owner");
            execute(connection, foodInsert(ownerId, true));

            try (ResultSet row = connection.createStatement().executeQuery(
                "SELECT user_id, archived FROM foods WHERE normalized_name = 'oats'"
            )) {
                assertTrue(row.next());
                assertEquals(ownerId, row.getLong("user_id"));
                assertTrue(row.getBoolean("archived"));
            }

            assertThrows(SQLException.class, () -> execute(connection, foodInsertWithoutOwner()));
            assertThrows(SQLException.class, () -> execute(connection, foodInsert(ownerId + 999, false)));
            assertEquals(1, count(connection,
                "SELECT COUNT(*) FROM information_schema.indexes " +
                    "WHERE table_name = 'foods' AND index_name = 'idx_foods_user_archived_normalized_name'"));
        }
    }

    @Test
    void upgradesAnEmptyV1SchemaWithoutInventingOwnership() throws Exception {
        String url = databaseUrl();
        prepareCompleteV1Schema(url);
        long ownerId;
        try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
            ownerId = insertUser(connection, "upgrade-owner");
        }

        MigrateResult upgrade = flyway(url).migrate();

        assertEquals(2, upgrade.migrationsExecuted);
        try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
            execute(connection, foodInsert(ownerId, false));
            try (ResultSet row = connection.createStatement().executeQuery(
                "SELECT archived FROM foods WHERE user_id = " + ownerId
            )) {
                assertTrue(row.next());
                assertFalse(row.getBoolean("archived"));
            }
        }
    }

    @Test
    void rejectsV1FoodsWhoseOwnerCannotBeSafelyInferred() throws Exception {
        String url = databaseUrl();
        prepareCompleteV1Schema(url);
        try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
            insertUser(connection, "legacy-user");
            execute(connection, foodInsertWithoutOwner());
        }

        assertThrows(FlywayException.class, () -> flyway(url).migrate());
    }

    /**
     * Both stop at V3. This suite is about the ownership contract V2 introduced and
     * the V3 state it has to keep working in, so it must not restate how many
     * migrations exist in total.
     */
    private static Flyway freshFlyway(String url) {
        return Flyway.configure()
            .dataSource(url, "sa", "")
            .locations("classpath:db/migration-h2")
            .baselineOnMigrate(true)
            .baselineVersion("1")
            .target(MigrationVersion.fromVersion("3"))
            .load();
    }

    private static Flyway flyway(String url) {
        return Flyway.configure()
            .dataSource(url, "sa", "")
            .locations("classpath:db/migration")
            .baselineOnMigrate(true)
            .baselineVersion("1")
            .target(MigrationVersion.fromVersion("3"))
            .load();
    }

    private static void prepareCompleteV1Schema(String url) throws SQLException {
        try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
            execute(connection, """
                CREATE TABLE users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    provider VARCHAR(30) NOT NULL,
                    provider_user_id VARCHAR(255) NOT NULL,
                    email VARCHAR(320) NOT NULL,
                    name VARCHAR(100),
                    profile_completed BOOLEAN NOT NULL,
                    timezone VARCHAR(50) NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL,
                    CONSTRAINT uk_users_provider_subject UNIQUE (provider, provider_user_id)
                )
                """);
            execute(connection, """
                CREATE TABLE user_profiles (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    height_cm NUMERIC(5, 2) NOT NULL,
                    weight_kg NUMERIC(5, 2) NOT NULL,
                    activity_level VARCHAR(20) NOT NULL,
                    goal_mode VARCHAR(20) NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL,
                    CONSTRAINT uk_user_profiles_user UNIQUE (user_id),
                    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users (id),
                    CONSTRAINT ck_user_profiles_height_positive CHECK (height_cm > 0),
                    CONSTRAINT ck_user_profiles_weight_positive CHECK (weight_kg > 0)
                )
                """);
            execute(connection, """
                CREATE TABLE user_targets (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    target_type VARCHAR(30) NOT NULL,
                    target_value NUMERIC(10, 2) NOT NULL,
                    due_date DATE,
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL,
                    CONSTRAINT uk_user_targets_type UNIQUE (user_id, target_type),
                    CONSTRAINT fk_user_targets_user FOREIGN KEY (user_id) REFERENCES users (id),
                    CONSTRAINT ck_user_targets_value_positive CHECK (target_value > 0)
                )
                """);
            execute(connection, """
                CREATE TABLE foods (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(200) NOT NULL,
                    normalized_name VARCHAR(200) NOT NULL,
                    serving_amount NUMERIC(10, 3) NOT NULL,
                    serving_unit VARCHAR(20) NOT NULL,
                    calories_kcal NUMERIC(10, 3) NOT NULL,
                    carbohydrates_g NUMERIC(10, 3) NOT NULL,
                    protein_g NUMERIC(10, 3) NOT NULL,
                    fat_g NUMERIC(10, 3) NOT NULL,
                    external_source VARCHAR(50),
                    external_food_id VARCHAR(200),
                    last_fetched_at DATE,
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL,
                    CONSTRAINT ck_foods_serving_amount_positive CHECK (serving_amount > 0),
                    CONSTRAINT ck_foods_calories_non_negative CHECK (calories_kcal >= 0),
                    CONSTRAINT ck_foods_carbohydrates_non_negative CHECK (carbohydrates_g >= 0),
                    CONSTRAINT ck_foods_protein_non_negative CHECK (protein_g >= 0),
                    CONSTRAINT ck_foods_fat_non_negative CHECK (fat_g >= 0)
                )
                """);
            execute(connection, "CREATE INDEX idx_foods_normalized_name ON foods (normalized_name)");
            execute(connection, "CREATE UNIQUE INDEX uk_foods_external_id " +
                "ON foods (external_source, external_food_id)");
            execute(connection, """
                CREATE TABLE meals (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    meal_date DATE NOT NULL,
                    meal_type VARCHAR(20) NOT NULL,
                    eaten_at TIMESTAMPTZ,
                    source_text TEXT,
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL,
                    CONSTRAINT fk_meals_user FOREIGN KEY (user_id) REFERENCES users (id)
                )
                """);
            execute(connection, "CREATE INDEX idx_meals_user_date_eaten ON meals (user_id, meal_date, eaten_at)");
            execute(connection, """
                CREATE TABLE meal_items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    meal_id BIGINT NOT NULL,
                    food_id BIGINT NOT NULL,
                    amount NUMERIC(10, 3) NOT NULL,
                    unit VARCHAR(20) NOT NULL,
                    calories_kcal NUMERIC(10, 3) NOT NULL,
                    carbohydrates_g NUMERIC(10, 3) NOT NULL,
                    protein_g NUMERIC(10, 3) NOT NULL,
                    fat_g NUMERIC(10, 3) NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL,
                    CONSTRAINT fk_meal_items_meal FOREIGN KEY (meal_id) REFERENCES meals (id),
                    CONSTRAINT fk_meal_items_food FOREIGN KEY (food_id) REFERENCES foods (id),
                    CONSTRAINT ck_meal_items_amount_positive CHECK (amount > 0),
                    CONSTRAINT ck_meal_items_calories_non_negative CHECK (calories_kcal >= 0),
                    CONSTRAINT ck_meal_items_carbohydrates_non_negative CHECK (carbohydrates_g >= 0),
                    CONSTRAINT ck_meal_items_protein_non_negative CHECK (protein_g >= 0),
                    CONSTRAINT ck_meal_items_fat_non_negative CHECK (fat_g >= 0)
                )
                """);
        }
    }

    private static String databaseUrl() throws SQLException {
        String url = "jdbc:h2:mem:food-migration-" + UUID.randomUUID() +
            ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1";
        try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
            execute(connection, "CREATE DOMAIN TIMESTAMPTZ AS TIMESTAMP WITH TIME ZONE");
        }
        return url;
    }

    private static String migrationResource(String path) throws IOException {
        try (InputStream input = FoodOwnershipMigrationTests.class.getResourceAsStream(path)) {
            if (input == null) {
                throw new IOException("Missing migration resource: " + path);
            }
            return new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    private static long insertUser(Connection connection, String providerUserId) throws SQLException {
        execute(connection,
            "INSERT INTO users " +
                "(provider, provider_user_id, email, name, profile_completed, timezone, created_at, updated_at) " +
                "VALUES ('GOOGLE', '" + providerUserId + "', '" + providerUserId +
                "@example.com', 'Owner', FALSE, 'UTC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
        );
        try (ResultSet row = connection.createStatement().executeQuery(
            "SELECT id FROM users WHERE provider_user_id = '" + providerUserId + "'"
        )) {
            row.next();
            return row.getLong(1);
        }
    }

    private static String foodInsert(long ownerId, boolean archived) {
        return "INSERT INTO foods " +
            "(user_id, archived, name, normalized_name, serving_amount, serving_unit, calories_kcal, " +
            "carbohydrates_g, protein_g, fat_g, created_at, updated_at) VALUES (" + ownerId + ", " + archived +
            ", 'Oats', 'oats', 100, 'g', 389, 66.3, 16.9, 6.9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)";
    }

    private static String foodInsertWithoutOwner() {
        return "INSERT INTO foods " +
            "(name, normalized_name, serving_amount, serving_unit, calories_kcal, carbohydrates_g, protein_g, " +
            "fat_g, created_at, updated_at) VALUES " +
            "('Legacy', 'legacy', 100, 'g', 100, 10, 10, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)";
    }

    private static int count(Connection connection, String sql) throws SQLException {
        try (ResultSet row = connection.createStatement().executeQuery(sql)) {
            row.next();
            return row.getInt(1);
        }
    }

    private static void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
